package com.bestool.dataprocessor.entity

import javax.persistence.*
import java.util.*

@Entity
@Table(name = "BT_DETALLE_FACTURA", schema = "QA_BESTOOLS_OWNER")
data class BTDetalleFactura(
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "QA_BESTOOLS_OWNER.SEQ_BT_DETALLE_FACTURA")
    @SequenceGenerator(name = "QA_BESTOOLS_OWNER.SEQ_BT_DETALLE_FACTURA", sequenceName = "QA_BESTOOLS_OWNER.SEQ_BT_DETALLE_FACTURA", allocationSize = 1)
    @Column(name = "BDF_ID", insertable = false, updatable = false) val id: Long = 0,
    @Column(name = "BDF_NUM_FACTURA") val numFactura: String,
    @Column(name = "BDF_REFERENCIA") val referencia: String?,
    @Column(name = "BDF_OPERADOR") val operador: String?,
    @Column(name = "BDF_FECHA_EMICION") val fechaEmision: Date?,
    @Column(name = "BDF_FECHA_VENCIMIENTO") val fechaVencimiento: Date?,
    @Column(name = "BDF_FECHA_CORTE") val fechaCorte: Date?,
    @Column(name = "BDF_MONEDA") val moneda: String?,
    @Column(name = "BDF_TIPO_MONEDA") val tipoMoneda: String?,
    @Column(name = "BDF_IVA") val iva: Double?,
    @Column(name = "BDF_SUBTOTAL") val subtotal: Double?,
    @Column(name = "BDF_IMPUESTOS") val impuestos: Double?,
    @Column(name = "BDF_TOTAL") val total: Double?,
    @Column(name = "BDF_TOTAL_LETRA") val totalLetra: String?,
    @Column(name = "BDF_SALDO_ANTERIOR") val saldoAnterior: Double?,
    @Column(name = "BDF_DESCUENTO") val descuento: Double?,
    @Column(name = "BDF_OTROS_CARGOS") val otrosCargos: Double?,
    @Column(name = "BDF_SUBTOTAL_2") val subtotal2: Double?,
    @Column(name = "BDF_IMPUESTOS_2") val impuestos2: Double?,
    @Column(name = "BDF_TOTAL_2") val total2: Double?,
    @Column(name = "BDF_TOTAL_FINAL") val totalFinal: Double?,
    @Column(name = "BDF_NOM_CLIENTE") val nombreCliente: String?,
    @Column(name = "BDF_DESC_CLIENTE") val descripcionCliente: String?,
    @Column(name = "BDF_SUCURSAL") val sucursal: String?,
    @Column(name = "BDF_NUM_CUENTA") val numeroCuenta: String?,
    @Column(name = "BDF_RFC") val rfc: String?,
    @Column(name = "BDF_REF_ADICIONAL") val referenciaAdicional: String?,
    @Column(name = "BDF_NOM_CLIENTE_AD") val nombreClienteAdicional: String?,
    @Column(name = "BDF_DOMICILIO") val domicilio: String?,
    @Column(name = "BDF_UBICACION") val ubicacion: String?,
    @Column(name = "BDF_LOCALIDAD") val localidad: String?,
    @Column(name = "BDF_ESTADO") val estado: String?,
    @Column(name = "BDF_MUNICIPIO") val municipio: String?,
    @Column(name = "BDF_CP") val codigoPostal: String?,
    @Column(name = "BDF_PAIS") val pais: String?,
    @Column(name = "BDF_DOM_FISCAL") val domicilioFiscal: String?,
    @Column(name = "BDF_UBI_FISCAL") val ubicacionFiscal: String?,
    @Column(name = "BDF_LOC_FISCAL") val localidadFiscal: String?,
    @Column(name = "BDF_ESTADO_FISCAL") val estadoFiscal: String?,
    @Column(name = "BDF_MUNICIPIO_FISCAL") val municipioFiscal: String?,
    @Column(name = "BDF_CP_FISCAL") val codigoPostalFiscal: String?,
    @Column(name = "BDF_NUM_FACTURACION") val numFacturacion: String?,
    @Column(name = "BDF_PAIS_FISCAL") val paisFiscal: String?,
    @Column(name = "BDF_NOTAS") val notas: String?,
    @Column(name = "BDF_FECHA_CREACION") val fechaCreacion: Date?,
    @Column(name = "BDF_ACTIVO") val activo: Int
) {
    constructor() : this(
        numFactura = "",
        referencia = null,
        operador = null,
        fechaEmision = null,
        fechaVencimiento = null,
        fechaCorte = null,
        moneda = null,
        tipoMoneda = null,
        iva = null,
        subtotal = null,
        impuestos = null,
        total = null,
        totalLetra = null,
        saldoAnterior = null,
        descuento = null,
        otrosCargos = null,
        subtotal2 = null,
        impuestos2 = null,
        total2 = null,
        totalFinal = null,
        nombreCliente = null,
        descripcionCliente = null,
        sucursal = null,
        numeroCuenta = null,
        rfc = null,
        referenciaAdicional = null,
        nombreClienteAdicional = null,
        domicilio = null,
        ubicacion = null,
        localidad = null,
        estado = null,
        municipio = null,
        codigoPostal = null,
        pais = null,
        domicilioFiscal = null,
        ubicacionFiscal = null,
        localidadFiscal = null,
        estadoFiscal = null,
        municipioFiscal = null,
        codigoPostalFiscal = null,
        numFacturacion = null,
        paisFiscal = null,
        notas = null,
        fechaCreacion = null,
        activo = 1
    )
}